feat: add husky support

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,8 +1,13 @@
 #!/bin/sh
-. "$(dirname "$0")/_/husky.sh"
 
-printf '\n[pre-commit] Running make lint...\n'
-make lint
+run_make() {
+  target="$1"
+  if ! make "$target" >/dev/null; then
+    printf '\n[pre-commit] %s failed.\n' "$target"
+    exit 1
+  fi
+}
 
-printf '\n[pre-commit] Running make check...\n'
-make check
+run_make lint
+run_make format
+run_make check
